name: PageLinks
version: 1.0.0
description: Add page link functionality to internal pages to links and image dialog
url: https://github.com/peda/statamic-page-links
developer: Peter Rainer
developer_url: https://www.peterrainer.at
